### PR TITLE
Wait for index to close before destroying it

### PR DESCRIPTION
**Pull request by nickva**
When the database is deleted index closing is racing with index
destruction (from hastings_vacuum). There is a good chance they'd both
try to acquire the internal LevelDB advisory file lock and one of them
will fail. This started happening a lot more frequently in Erlang
versions 19.0 and higher since port communication was optimized and
made more asynchronous.

Therefore when destroying the index, first check if there is an index
process, and if there is way, make sure to close it and wait for it to
exit then call destroy. The race is not completely eliminated but it
should reduce the chances.

BugzID: 106393

### CODE REVIEW

**Comment by jiangphcn** [comment]
Hey @nickva thanks for this PR. We ever made similar change and triggered test in build server using erl 20. But still see some failure. Some details can be found from https://github.com/cloudant-labs/easton/pull/8#issuecomment-389500887.

The whole progress is recorded in PR https://github.com/cloudant-labs/easton/pull/8

**Comment by nickva** [comment]
@jiangphcn I tried it and seemed to work locally. Notice that in the diff you tried there was bug:

https://gist.github.com/davisp/c34f694f659f722c00e19c4b4a87c49a#file-hastings-diff-L26

`GeoDirParts = filename:split(GeoDir)` will produce a list of strings when it split. But `BaseParts` is going to be a list of binaries. That means strip_leading function won't strip the prefix correctly (because it relies on exact matching) so it would never find the indexer process in the ets table and just call destroy right away https://gist.github.com/davisp/c34f694f659f722c00e19c4b4a87c49a#file-hastings-diff-L16

With the correct fix it seems to work better locally, that I could reproduce it before the fix and I couldn't after. The race condition is still there but it's just less likely to happen.

LevelDb really cannot handle concurrent access and needs external serialization so maybe it's worth either adding locks on the port side or always guarantee everything goes through one process. But that's a bigger change.

**Comment by davisp** [comment]
@jiangphcn Can you point me at where the 20.0 test build/branch is? Might be best to just queue up some runs of this version against that approach to see if this fixes things.

**Comment by nickva** [comment]
Got a pass with Erlang 20.3.7

https://build2.cloudant.com/job/dbnext/7002/label=docker-local-jessie,type=paas/consoleFull

```
module 'hastings_delete_db_test'
  Hastings Delete Database Tests
    hastings_delete_db_test:65: should_delete_index_after_deleting_database...[0.653 s] ok
    hastings_delete_db_test:104: should_rename_index_after_deleting_database...[0.455 s] ok
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
    [done in 1.387 s]
  [done in 1.527 s]
```

**Comment by nickva** [comment]
One more pass https://build2.cloudant.com/job/dbnext/7004/label=docker-local-jessie,type=paas/console

**Comment by nickva** [comment]
3rd one
 
https://build2.cloudant.com/job/dbnext/7006/label=docker-local-jessie,type=paas/console

```
module 'hastings_httpd_util'
module 'hastings_delete_db_test'
  Hastings Delete Database Tests
    hastings_delete_db_test:65: should_delete_index_after_deleting_database...[0.502 s] ok
    hastings_delete_db_test:104: should_rename_index_after_deleting_database...[0.515 s] ok
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
    [done in 1.288 s]
  [done in 1.411 s]
module 'hastings_ken_tests'
  Ken Tests
```

**Comment by nickva** [comment]
Forgot to mention the original fix for this was written by @davisp I just fixed a small thing and verified it worked

**Comment by jiangphcn** [comment]
agreed with @davisp and good catch on findings of that differnce. In original code, one Pid is printed and is used to stop hastings_index. So don't think more that it is valid or not.  
```
src/hastings_index.erl:100:<0.17432.4>: before hastings_index:stop Pid ... 
<0.17422.4>
```
Hey @davisp, in the past, I used ERLANG_VERSION `20.3.6` and BRANCH `origin/erl20-0515` to trigger build. I saw that @nickva did the similar thing. That's fine :-)

**Pull request merged**
